version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: devpilot-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: devpilot
      POSTGRES_USER: devpilot
      POSTGRES_PASSWORD: devpilot123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: